title:            Shushruth
locale:           en_US
url:              https://sshruth.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Shushruth
  avatar: shushruth.jpg
  bio: Neuroscientist
  email:
  disqus-shortname:
  twitter: #
  facebook: #
  google:
    plus:
    analytics: UA-120627681-1
    scholar:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #
  stackoverflow: #
  linkedin: #
  instagram: #
  lastfm: #
  tumblr: #
  pinterest: #
  foursquare: #
  steam: #
  dribbble: #
  youtube: #
  soundcloud: #

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
